### ISSUE TITLE
Use with Pyinstaller causes ImportError: module 'apiflask' has no attribute 'settings'

### ISSUE THREAD

**Issue by chongjing001** [apiflask/apiflask#368] opened 2022-11-10 04:31 UTC
pyinstaller  

Traceback (most recent call last):
  File "werkzeug\utils.py", line 556, in import_string
AttributeError: module 'apiflask' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "werkzeug\utils.py", line 558, in import_string
ImportError: module 'apiflask' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
  File "apiflask\app.py", line 338, in __init__
  File "flask\config.py", line 174, in from_object
  File "werkzeug\utils.py", line 563, in import_string
  File "werkzeug\_compat.py", line 147, in reraise
  File "werkzeug\utils.py", line 558, in import_string
werkzeug.utils.ImportStringError: import_string() failed for 'apiflask.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'apiflask' found in 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI324362\\apiflask\\__init__.pyc'.
- 'apiflask.settings' not found.

Original exception:

ImportError: module 'apiflask' has no attribute 'settings'
[24324] Failed to execute script manage
Environment:

- Python version:3.7.4
- Flask version:1.1.1
- APIFlask version:1.1.3

**Comment by greyli** [comment] 2022-12-22 14:26
Can you provide a minimal example that can reproduce this issue?

**Comment by greyli** [comment] 2023-02-18 04:27
Closed as stale.

**Comment by tkzt** [comment] 2023-03-18 08:59
Since `settings` is not imported directly in `apiflask.__init__.py` (and maybe should not either), we could use the argument `--hidden-import` when packaging to remind PyInstaller to import such modules.

A workable packaging command:

```
python -m PyInstaller -F ./main.py --hidden-import=apiflask.settings
```

**Comment by greyli** [comment] 2023-03-18 09:47
Thank you @tkzt!

Closing this issue now.

**Closed by greyli** 2023-03-18 09:47 UTC
Labels: question, need more info
