### ISSUE TITLE
Spec cli command does not works with flask 3.0.3

### ISSUE THREAD

**Issue by IvanFaja** [apiflask/apiflask#582] opened 2024-07-09 16:58 UTC
Environment:

- Python version: 3.10
- Flask version:3.0.3
- APIFlask version:2.1.2

**Comment by uncle-lv** [comment] 2024-07-10 12:41
Please provide a minimal reproducible example and the full exception traceback information.

**Comment by IvanFaja** [comment] 2024-07-10 14:31
create a minimal server:
Flask version:3.0.3
APIFlask version:2.1.2

`from apiflask import APIFlask

def build_app():
    app = APIFlask(__name__, spec_path='/openapi.json')

    @app.get("/dummy")
    def health_check():
        return "hello :)"

    return app
`

and the run the command line got generate the scpec:

`flask --app 'app:build_app()' spec`

The progarm console output is 

`Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'spec'.`

if downgrade to 2.1.1 works as expected

**Comment by uncle-lv** [comment] 2024-07-11 17:57
This is caused by a configuration error in `pyproject.toml`. I have fixed it in #583 .

**Comment by greyli** [comment] 2024-07-13 11:12
Fixed in #583

**Closed by greyli** 2024-07-13 11:12 UTC
Labels: bug

**Comment by greyli** [comment] 2024-07-14 03:27
The [2.1.3 version](https://github.com/apiflask/apiflask/releases/tag/2.1.3) was released. Thanks for reporting this issue, and thanks @uncle-lv for the quick fix!
